### ISSUE TITLE
items not linking to channels

### ISSUE THREAD

**Issue by stamateviorel** [sichelz1/sonos-coordinator#1]
Hello wow great job with the script i gave it a test everything fine it loads up creates the proxy items but doesnt link them with the channels like you specified. I am running openhab 3.2 on debian no errors in the log.

**Comment by sichelz1** [comment]
Which of your items are not bound to a channel? The items which control the group (zoneVolumeItemName , groupSwichterItemName and zoneMuteItemName) will never be bound to a channel as they are only used to forward the states to the items bound to the sonos things. 
All other items will be created on demand (e.g. when you do not have an item bound to the volume channel of a thing yet). These items should then be bound to a channel.

**Comment by stamateviorel** [comment]
I did not had time to replay but after deleting the items and adding the sonos thing via ui the channels got populated with items from the script before i had the thing configurated in the .things file maybe that is the reason that your script looks in registry of the thing not files ?

**Comment by sichelz1** [comment]
Hmm.. since i switched to OH 3 i never used the file based configuration again... It could be a bug in OH, that the file based things are not being reported by the ThingRegistry.
It would not help if the script would parse the .thing files as it requires the registry for establishing the links to the channels and if the registry is not aware of the things, those calls would most propably fail.
But i'm happy to hear that it worked for you using the ui :-)
